#include "circt/Dialect/HW/HWOps.h"
#include "circt/Dialect/HW/HWPasses.h"
#include "circt/Dialect/HW/HWTypes.h"
#include "mlir/Pass/Pass.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/ImmutableList.h"
#include "llvm/Support/Regex.h"

namespace circt {
namespace hw {
#define GEN_PASS_DEF_HWEXPUNGEMODULE
#include "circt/Dialect/HW/Passes.h.inc"
} // namespace hw
} // namespace circt

namespace {
struct HWExpungeModulePass : circt::hw::impl::HWExpungeModuleBase<HWExpungeModulePass> {
  void runOnOperation() override;
};

llvm::Regex prefixSpecRegex = {"^[a-zA-Z0-9_]+:([a-zA-Z0-9_](.[a-zA-Z0-9_])*)=([a-zA-Z0-9_]+)$", llvm::Regex::NoFlags};

struct InstPathSeg {
  llvm::StringRef seg;

  InstPathSeg(llvm::StringRef seg) : seg(seg) {}
  const llvm::StringRef& getSeg() const { return seg; }
  operator llvm::StringRef() const { return seg; }

  void Profile(llvm::FoldingSetNodeID &ID) const {
    ID.AddString(seg);
  }
};
using InstPath = llvm::ImmutableList<InstPathSeg>;
llvm::Twine defaultPrefix(InstPath path) {
  if(path.isEmpty()) return "_";
  return path.getHead().getSeg() + "_" + defaultPrefix(path.getTail());
}
} // namespace

void HWExpungeModulePass::runOnOperation() {
  auto root = getOperation();
  llvm::DenseMap<mlir::StringRef, circt::hw::HWModuleOp> allModules;
  root.walk([&](circt::hw::HWModuleOp mod) {
    allModules[mod.getName()] = mod;
  });
  // Reverse-topo order generated by module instances.
  // The topo sorted order does not change throught out the operation. It only gets weakened, but
  // still valid.
  llvm::SmallVector<circt::hw::HWModuleOp> revTopo;
  llvm::DenseSet<mlir::StringRef> visited;
  auto visit = [&allModules, &visited, &revTopo](auto &self, circt::hw::HWModuleOp mod) -> void {
    if(visited.contains(mod.getName())) return;
    visited.insert(mod.getName());

    mod.walk([&](circt::hw::InstanceOp inst) {
      auto instModName = inst.getModuleName();
      auto instMod = allModules.lookup(instModName);
      if(!instMod) inst.emitError("Unknown module ") << instModName;
      self(self, instMod);
    });

    // Reverse topo order, insert on stack pop
    revTopo.push_back(mod);
  };
  for(auto &[_, mod] : allModules) visit(visit, mod);
  assert(revTopo.size() == allModules.size());

  // Instance path.
  InstPath::Factory pathFactory;

  // Process port prefix specifications
  // (Module name, Instance path) -> Prefix
  llvm::DenseMap<std::pair<mlir::StringRef, InstPath>, mlir::StringRef> designatedPrefixes;
  std::string matchError;
  llvm::SmallVector<llvm::StringRef> matches;
  bool containsFailure = false;
  for(const auto &raw : portPrefixes) {
    if(prefixSpecRegex.match(raw, &matches, &matchError)) {
      // matches[0] is module name
      // matches[1] is full instance path
      // matches[2:-1] is the instance path segments
      // matches[-1] is the prefix

      if(!allModules.contains(matches[0])) {
        llvm::errs() << "Module not found in port prefix specification: " << matches[0] << "\n";
        llvm::errs() << "From specification: " << raw << "\n";
        containsFailure = true;
        continue;
      }

      // TODO: check instance path, or check which prefix specification is not
      // used at the end of this pass
      InstPath path;
      for(size_t i = 2; i < matches.size() - 1; ++i)
        path = pathFactory.add(matches[i], path);
      designatedPrefixes.insert({{matches[0], path}, matches[matches.size() - 1]});
    } else {
      llvm::errs() << "Invalid port prefix specification: " << raw << "\n";
      llvm::errs() << "Error: " << matchError << "\n";
      containsFailure = true;
    }
  }

  if(containsFailure) return signalPassFailure();

  // Instance path * prefix name
  using ReplacedDescendent = std::pair<InstPath, std::string>;
  // This map holds the expunged descendents of a module
  llvm::DenseMap<llvm::StringRef, llvm::SmallVector<ReplacedDescendent>> expungedDescendents;
  for(auto &expunging : this->modules) {
    // Clear expungedDescendents
    for(auto &it : expungedDescendents)
      it.getSecond().clear();

    auto expungingMod = allModules.lookup(expunging);
    if(!expungingMod) continue; // Ignored missing modules
    auto expungingModTy = expungingMod.getModuleType();
    auto expungingModPorts = expungingModTy.getPorts();

    auto createPortsOn = [&expungingModPorts](
      circt::hw::HWModuleOp mod,
      const std::string &prefix,
      auto genOutput,
      auto emitInput
    ) {
      mlir::OpBuilder builder(mod);
      // Create ports using *REVERSE* direction of their definitions
      for(auto &port : expungingModPorts) {
        auto defaultName = prefix + port.name.getValue();
        // FIXME: solve naming collisions
        auto finalName = defaultName;
        if(port.dir == circt::hw::PortInfo::Input) {
          auto val = genOutput(port);
          assert(val.getType() == port.type);
          mod.appendOutput(finalName, val);
        } else if(port.dir == circt::hw::PortInfo::Output) {
          auto [_, arg] = mod.appendInput(finalName, port.type);
          emitInput(port, arg);
        }
      }
    };

    for(auto &processing : revTopo) {
      std::optional<decltype(expungedDescendents.lookup("")) *> outerExpDesc = {};
      auto getOuterExpDesc = [&]() -> decltype(**outerExpDesc) {
        if(!outerExpDesc.has_value())
          outerExpDesc = { &expungedDescendents.insert({processing.getName(), {}}).first->getSecond() };
        return **outerExpDesc;
      };

      processing.walk([&](circt::hw::InstanceOp inst) {
        // TODO: check if this attribute exists
        auto instName = llvm::cast<mlir::StringAttr>(inst->getAttr("sym_name")).getValue();
        auto instMod = allModules.lookup(inst.getModuleName());

        llvm::DenseMap<llvm::StringRef, mlir::Value> instOMap;
        assert(instMod.getOutputNames().size() == inst.getResults().size());
        for(auto [oname, oval] : llvm::zip(instMod.getOutputNames(), inst.getResults()))
          instOMap[llvm::cast<mlir::StringAttr>(oname).getValue()] = oval;
        
        auto instExpDesc = expungedDescendents.find(inst.getModuleName());

        if(inst.getModuleName() == expunging) {
          // Handle the directly expunged module
          // input maps also useful for directly expunged instance
          llvm::DenseMap<llvm::StringRef, mlir::Value> instIMap;
          assert(instMod.getInputNames().size() == inst.getInputs().size());
          for(auto [iname, ival] : llvm::zip(instMod.getInputNames(), inst.getInputs()))
            instIMap[llvm::cast<mlir::StringAttr>(iname).getValue()] = ival;
          
          auto singletonPath = pathFactory.create(instName);

          auto designatedPrefix = designatedPrefixes.find({processing.getName(), singletonPath});
          std::string prefix = designatedPrefix != designatedPrefixes.end() ? designatedPrefix->getSecond().str() : (instName + "__").str();
          createPortsOn(processing, prefix, [&](circt::hw::ModulePort port) {
            // Generate output for outer module, so input for us
            return instIMap.at(port.name);
          }, [&](circt::hw::ModulePort port, mlir::Value val) {
            // Generated input for outer module, replace inst results
            assert(instOMap.contains(port.name));
            instOMap[port.name].replaceAllUsesWith(val);
          });

          getOuterExpDesc().emplace_back(singletonPath, prefix);
          assert(instExpDesc == expungedDescendents.end() || instExpDesc->getSecond().size() == 0);

          inst->remove();
        } else if(instExpDesc != expungedDescendents.end()) {
          // Handle all transitive descendents
          if(instExpDesc->second.size() == 0) return;
          llvm::DenseMap<llvm::StringRef, mlir::Value> newInputs;
          for(const auto &exp : instExpDesc->second) {
            auto newPath = pathFactory.add(instName, exp.first);
            auto designatedPrefix = designatedPrefixes.find({processing.getName(), newPath});
            std::string prefix = designatedPrefix != designatedPrefixes.end() ? designatedPrefix->getSecond().str() : defaultPrefix(newPath).str();

            createPortsOn(processing, prefix, [&](circt::hw::ModulePort port) {
              // Generate output for outer module, directly forward from inner inst
              auto it = instOMap.find_as((exp.second + port.name.getValue()).str());
              assert(it != instOMap.end());
              return it->second;
            }, [&](circt::hw::ModulePort port, mlir::Value val) {
              // Generated input for outer module, replace inst results
              newInputs.insert({(exp.second + port.name.getValue()).str(), val});
            });
          }

          auto newInputsRange = llvm::map_to_vector(
            llvm::index_range(inst.getInputs().size(), instMod.getNumInputPorts()),
            [&](size_t i) {
              auto iname = instMod.getInputName(i);
              return newInputs.find_as(iname)->second;
            }
          );
          inst->insertOperands(inst.getInputs().size(), newInputsRange);
        }
      });
    }
  }
}

std::unique_ptr<mlir::Pass> circt::hw::createHWExpungeModulePass() {
  return std::make_unique<HWExpungeModulePass>();
}